[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore ZooCare.API/ZooCare.API.csproj"]

[phases.build]
cmds = ["dotnet build ZooCare.API/ZooCare.API.csproj -c Release --no-restore"]

[start]
cmd = "dotnet ZooCare.API/bin/Release/net8.0/ZooCare.API.dll"

