services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ZooCare_Str0ng!Pass"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "SELECT 1" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=ZooCareDB;User Id=sa;Password=ZooCare_Str0ng!Pass;TrustServerCertificate=True;Encrypt=False"
    expose:
      - "10000"
    depends_on:
      mssql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # точка входу: http://localhost:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  mssql-data:
